// [TYNY_DATA_TABLE][1.0.0]
// This code is generated by TinyDataTable.
// Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
using System;

namespace TinyDataTable
{
    public static class RecordGenericType
    {
        public static int TypeCount => 20;

        public static Type  GetType(int numField)
        {
            Type type = numField switch
            {
                0 => typeof(RecordEmpty),
                1 => typeof(Record<>),
                2 => typeof(Record<,>),
                3 => typeof(Record<,,>),
                4 => typeof(Record<,,,>),
                5 => typeof(Record<,,,,>),
                6 => typeof(Record<,,,,,>),
                7 => typeof(Record<,,,,,,>),
                8 => typeof(Record<,,,,,,,>),
                9 => typeof(Record<,,,,,,,,>),
                10 => typeof(Record<,,,,,,,,,>),
                11 => typeof(Record<,,,,,,,,,,>),
                12 => typeof(Record<,,,,,,,,,,,>),
                13 => typeof(Record<,,,,,,,,,,,,>),
                14 => typeof(Record<,,,,,,,,,,,,,>),
                15 => typeof(Record<,,,,,,,,,,,,,,>),
                16 => typeof(Record<,,,,,,,,,,,,,,,>),
                17 => typeof(Record<,,,,,,,,,,,,,,,,>),
                18 => typeof(Record<,,,,,,,,,,,,,,,,,>),
                19 => typeof(Record<,,,,,,,,,,,,,,,,,,>),
                20 => typeof(Record<,,,,,,,,,,,,,,,,,,,>),
                _ => throw new IndexOutOfRangeException(),
            };
            return type;
        }
    }

    [Serializable]
    public struct RecordEmpty : IRecord
    {
        public RecordHeader header;
        public RecordData[] recordData;

        public RecordHeader Header { set => header = value; get => header; }
        public Type[] GetFieldTypes() => Type.EmptyTypes;
        public IRecordData GetRecord(int rowIndex) => recordData[rowIndex];

        [Serializable]
        public struct RecordData : IRecordData
        {
            public RecordDataHeader header;
            public RecordDataHeader Header {set => header = value; get => header;}
        }
    }

    [Serializable]
    public struct Record<T0> : IRecord
    {
        public RecordHeader header;
        public RecordData[] recordData;
        private static Type[] _fieldTypes = new []{typeof(T0)};
        public RecordHeader Header { set => header = value; get => header; }
        public Type[] GetFieldTypes() => _fieldTypes;
        public IRecordData GetRecord(int rowIndex) => recordData[rowIndex];

        [Serializable]
        public struct RecordData : IRecordData
        {
            public RecordDataHeader header;
            public RecordDataHeader Header {set => header = value; get => header;}
            public T0 Field0;
        }
    }

    [Serializable]
    public struct Record<T0,T1> : IRecord
    {
        public RecordHeader header;
        public RecordData[] recordData;
        private static Type[] _fieldTypes = new []{typeof(T0),typeof(T1)};
        public RecordHeader Header { set => header = value; get => header; }
        public Type[] GetFieldTypes() => _fieldTypes;
        public IRecordData GetRecord(int rowIndex) => recordData[rowIndex];

        [Serializable]
        public struct RecordData : IRecordData
        {
            public RecordDataHeader header;
            public RecordDataHeader Header {set => header = value; get => header;}
            public T0 Field0;
            public T1 Field1;
        }
    }

    [Serializable]
    public struct Record<T0,T1,T2> : IRecord
    {
        public RecordHeader header;
        public RecordData[] recordData;
        private static Type[] _fieldTypes = new []{typeof(T0),typeof(T1),typeof(T2)};
        public RecordHeader Header { set => header = value; get => header; }
        public Type[] GetFieldTypes() => _fieldTypes;
        public IRecordData GetRecord(int rowIndex) => recordData[rowIndex];

        [Serializable]
        public struct RecordData : IRecordData
        {
            public RecordDataHeader header;
            public RecordDataHeader Header {set => header = value; get => header;}
            public T0 Field0;
            public T1 Field1;
            public T2 Field2;
        }
    }

    [Serializable]
    public struct Record<T0,T1,T2,T3> : IRecord
    {
        public RecordHeader header;
        public RecordData[] recordData;
        private static Type[] _fieldTypes = new []{typeof(T0),typeof(T1),typeof(T2),typeof(T3)};
        public RecordHeader Header { set => header = value; get => header; }
        public Type[] GetFieldTypes() => _fieldTypes;
        public IRecordData GetRecord(int rowIndex) => recordData[rowIndex];

        [Serializable]
        public struct RecordData : IRecordData
        {
            public RecordDataHeader header;
            public RecordDataHeader Header {set => header = value; get => header;}
            public T0 Field0;
            public T1 Field1;
            public T2 Field2;
            public T3 Field3;
        }
    }

    [Serializable]
    public struct Record<T0,T1,T2,T3,T4> : IRecord
    {
        public RecordHeader header;
        public RecordData[] recordData;
        private static Type[] _fieldTypes = new []{typeof(T0),typeof(T1),typeof(T2),typeof(T3),typeof(T4)};
        public RecordHeader Header { set => header = value; get => header; }
        public Type[] GetFieldTypes() => _fieldTypes;
        public IRecordData GetRecord(int rowIndex) => recordData[rowIndex];

        [Serializable]
        public struct RecordData : IRecordData
        {
            public RecordDataHeader header;
            public RecordDataHeader Header {set => header = value; get => header;}
            public T0 Field0;
            public T1 Field1;
            public T2 Field2;
            public T3 Field3;
            public T4 Field4;
        }
    }

    [Serializable]
    public struct Record<T0,T1,T2,T3,T4,T5> : IRecord
    {
        public RecordHeader header;
        public RecordData[] recordData;
        private static Type[] _fieldTypes = new []{typeof(T0),typeof(T1),typeof(T2),typeof(T3),typeof(T4),typeof(T5)};
        public RecordHeader Header { set => header = value; get => header; }
        public Type[] GetFieldTypes() => _fieldTypes;
        public IRecordData GetRecord(int rowIndex) => recordData[rowIndex];

        [Serializable]
        public struct RecordData : IRecordData
        {
            public RecordDataHeader header;
            public RecordDataHeader Header {set => header = value; get => header;}
            public T0 Field0;
            public T1 Field1;
            public T2 Field2;
            public T3 Field3;
            public T4 Field4;
            public T5 Field5;
        }
    }

    [Serializable]
    public struct Record<T0,T1,T2,T3,T4,T5,T6> : IRecord
    {
        public RecordHeader header;
        public RecordData[] recordData;
        private static Type[] _fieldTypes = new []{typeof(T0),typeof(T1),typeof(T2),typeof(T3),typeof(T4),typeof(T5),typeof(T6)};
        public RecordHeader Header { set => header = value; get => header; }
        public Type[] GetFieldTypes() => _fieldTypes;
        public IRecordData GetRecord(int rowIndex) => recordData[rowIndex];

        [Serializable]
        public struct RecordData : IRecordData
        {
            public RecordDataHeader header;
            public RecordDataHeader Header {set => header = value; get => header;}
            public T0 Field0;
            public T1 Field1;
            public T2 Field2;
            public T3 Field3;
            public T4 Field4;
            public T5 Field5;
            public T6 Field6;
        }
    }

    [Serializable]
    public struct Record<T0,T1,T2,T3,T4,T5,T6,T7> : IRecord
    {
        public RecordHeader header;
        public RecordData[] recordData;
        private static Type[] _fieldTypes = new []{typeof(T0),typeof(T1),typeof(T2),typeof(T3),typeof(T4),typeof(T5),typeof(T6),typeof(T7)};
        public RecordHeader Header { set => header = value; get => header; }
        public Type[] GetFieldTypes() => _fieldTypes;
        public IRecordData GetRecord(int rowIndex) => recordData[rowIndex];

        [Serializable]
        public struct RecordData : IRecordData
        {
            public RecordDataHeader header;
            public RecordDataHeader Header {set => header = value; get => header;}
            public T0 Field0;
            public T1 Field1;
            public T2 Field2;
            public T3 Field3;
            public T4 Field4;
            public T5 Field5;
            public T6 Field6;
            public T7 Field7;
        }
    }

    [Serializable]
    public struct Record<T0,T1,T2,T3,T4,T5,T6,T7,T8> : IRecord
    {
        public RecordHeader header;
        public RecordData[] recordData;
        private static Type[] _fieldTypes = new []{typeof(T0),typeof(T1),typeof(T2),typeof(T3),typeof(T4),typeof(T5),typeof(T6),typeof(T7),typeof(T8)};
        public RecordHeader Header { set => header = value; get => header; }
        public Type[] GetFieldTypes() => _fieldTypes;
        public IRecordData GetRecord(int rowIndex) => recordData[rowIndex];

        [Serializable]
        public struct RecordData : IRecordData
        {
            public RecordDataHeader header;
            public RecordDataHeader Header {set => header = value; get => header;}
            public T0 Field0;
            public T1 Field1;
            public T2 Field2;
            public T3 Field3;
            public T4 Field4;
            public T5 Field5;
            public T6 Field6;
            public T7 Field7;
            public T8 Field8;
        }
    }

    [Serializable]
    public struct Record<T0,T1,T2,T3,T4,T5,T6,T7,T8,T9> : IRecord
    {
        public RecordHeader header;
        public RecordData[] recordData;
        private static Type[] _fieldTypes = new []{typeof(T0),typeof(T1),typeof(T2),typeof(T3),typeof(T4),typeof(T5),typeof(T6),typeof(T7),typeof(T8),typeof(T9)};
        public RecordHeader Header { set => header = value; get => header; }
        public Type[] GetFieldTypes() => _fieldTypes;
        public IRecordData GetRecord(int rowIndex) => recordData[rowIndex];

        [Serializable]
        public struct RecordData : IRecordData
        {
            public RecordDataHeader header;
            public RecordDataHeader Header {set => header = value; get => header;}
            public T0 Field0;
            public T1 Field1;
            public T2 Field2;
            public T3 Field3;
            public T4 Field4;
            public T5 Field5;
            public T6 Field6;
            public T7 Field7;
            public T8 Field8;
            public T9 Field9;
        }
    }

    [Serializable]
    public struct Record<T0,T1,T2,T3,T4,T5,T6,T7,T8,T9,T10> : IRecord
    {
        public RecordHeader header;
        public RecordData[] recordData;
        private static Type[] _fieldTypes = new []{typeof(T0),typeof(T1),typeof(T2),typeof(T3),typeof(T4),typeof(T5),typeof(T6),typeof(T7),typeof(T8),typeof(T9),typeof(T10)};
        public RecordHeader Header { set => header = value; get => header; }
        public Type[] GetFieldTypes() => _fieldTypes;
        public IRecordData GetRecord(int rowIndex) => recordData[rowIndex];

        [Serializable]
        public struct RecordData : IRecordData
        {
            public RecordDataHeader header;
            public RecordDataHeader Header {set => header = value; get => header;}
            public T0 Field0;
            public T1 Field1;
            public T2 Field2;
            public T3 Field3;
            public T4 Field4;
            public T5 Field5;
            public T6 Field6;
            public T7 Field7;
            public T8 Field8;
            public T9 Field9;
            public T10 Field10;
        }
    }

    [Serializable]
    public struct Record<T0,T1,T2,T3,T4,T5,T6,T7,T8,T9,T10,T11> : IRecord
    {
        public RecordHeader header;
        public RecordData[] recordData;
        private static Type[] _fieldTypes = new []{typeof(T0),typeof(T1),typeof(T2),typeof(T3),typeof(T4),typeof(T5),typeof(T6),typeof(T7),typeof(T8),typeof(T9),typeof(T10),typeof(T11)};
        public RecordHeader Header { set => header = value; get => header; }
        public Type[] GetFieldTypes() => _fieldTypes;
        public IRecordData GetRecord(int rowIndex) => recordData[rowIndex];

        [Serializable]
        public struct RecordData : IRecordData
        {
            public RecordDataHeader header;
            public RecordDataHeader Header {set => header = value; get => header;}
            public T0 Field0;
            public T1 Field1;
            public T2 Field2;
            public T3 Field3;
            public T4 Field4;
            public T5 Field5;
            public T6 Field6;
            public T7 Field7;
            public T8 Field8;
            public T9 Field9;
            public T10 Field10;
            public T11 Field11;
        }
    }

    [Serializable]
    public struct Record<T0,T1,T2,T3,T4,T5,T6,T7,T8,T9,T10,T11,T12> : IRecord
    {
        public RecordHeader header;
        public RecordData[] recordData;
        private static Type[] _fieldTypes = new []{typeof(T0),typeof(T1),typeof(T2),typeof(T3),typeof(T4),typeof(T5),typeof(T6),typeof(T7),typeof(T8),typeof(T9),typeof(T10),typeof(T11),typeof(T12)};
        public RecordHeader Header { set => header = value; get => header; }
        public Type[] GetFieldTypes() => _fieldTypes;
        public IRecordData GetRecord(int rowIndex) => recordData[rowIndex];

        [Serializable]
        public struct RecordData : IRecordData
        {
            public RecordDataHeader header;
            public RecordDataHeader Header {set => header = value; get => header;}
            public T0 Field0;
            public T1 Field1;
            public T2 Field2;
            public T3 Field3;
            public T4 Field4;
            public T5 Field5;
            public T6 Field6;
            public T7 Field7;
            public T8 Field8;
            public T9 Field9;
            public T10 Field10;
            public T11 Field11;
            public T12 Field12;
        }
    }

    [Serializable]
    public struct Record<T0,T1,T2,T3,T4,T5,T6,T7,T8,T9,T10,T11,T12,T13> : IRecord
    {
        public RecordHeader header;
        public RecordData[] recordData;
        private static Type[] _fieldTypes = new []{typeof(T0),typeof(T1),typeof(T2),typeof(T3),typeof(T4),typeof(T5),typeof(T6),typeof(T7),typeof(T8),typeof(T9),typeof(T10),typeof(T11),typeof(T12),typeof(T13)};
        public RecordHeader Header { set => header = value; get => header; }
        public Type[] GetFieldTypes() => _fieldTypes;
        public IRecordData GetRecord(int rowIndex) => recordData[rowIndex];

        [Serializable]
        public struct RecordData : IRecordData
        {
            public RecordDataHeader header;
            public RecordDataHeader Header {set => header = value; get => header;}
            public T0 Field0;
            public T1 Field1;
            public T2 Field2;
            public T3 Field3;
            public T4 Field4;
            public T5 Field5;
            public T6 Field6;
            public T7 Field7;
            public T8 Field8;
            public T9 Field9;
            public T10 Field10;
            public T11 Field11;
            public T12 Field12;
            public T13 Field13;
        }
    }

    [Serializable]
    public struct Record<T0,T1,T2,T3,T4,T5,T6,T7,T8,T9,T10,T11,T12,T13,T14> : IRecord
    {
        public RecordHeader header;
        public RecordData[] recordData;
        private static Type[] _fieldTypes = new []{typeof(T0),typeof(T1),typeof(T2),typeof(T3),typeof(T4),typeof(T5),typeof(T6),typeof(T7),typeof(T8),typeof(T9),typeof(T10),typeof(T11),typeof(T12),typeof(T13),typeof(T14)};
        public RecordHeader Header { set => header = value; get => header; }
        public Type[] GetFieldTypes() => _fieldTypes;
        public IRecordData GetRecord(int rowIndex) => recordData[rowIndex];

        [Serializable]
        public struct RecordData : IRecordData
        {
            public RecordDataHeader header;
            public RecordDataHeader Header {set => header = value; get => header;}
            public T0 Field0;
            public T1 Field1;
            public T2 Field2;
            public T3 Field3;
            public T4 Field4;
            public T5 Field5;
            public T6 Field6;
            public T7 Field7;
            public T8 Field8;
            public T9 Field9;
            public T10 Field10;
            public T11 Field11;
            public T12 Field12;
            public T13 Field13;
            public T14 Field14;
        }
    }

    [Serializable]
    public struct Record<T0,T1,T2,T3,T4,T5,T6,T7,T8,T9,T10,T11,T12,T13,T14,T15> : IRecord
    {
        public RecordHeader header;
        public RecordData[] recordData;
        private static Type[] _fieldTypes = new []{typeof(T0),typeof(T1),typeof(T2),typeof(T3),typeof(T4),typeof(T5),typeof(T6),typeof(T7),typeof(T8),typeof(T9),typeof(T10),typeof(T11),typeof(T12),typeof(T13),typeof(T14),typeof(T15)};
        public RecordHeader Header { set => header = value; get => header; }
        public Type[] GetFieldTypes() => _fieldTypes;
        public IRecordData GetRecord(int rowIndex) => recordData[rowIndex];

        [Serializable]
        public struct RecordData : IRecordData
        {
            public RecordDataHeader header;
            public RecordDataHeader Header {set => header = value; get => header;}
            public T0 Field0;
            public T1 Field1;
            public T2 Field2;
            public T3 Field3;
            public T4 Field4;
            public T5 Field5;
            public T6 Field6;
            public T7 Field7;
            public T8 Field8;
            public T9 Field9;
            public T10 Field10;
            public T11 Field11;
            public T12 Field12;
            public T13 Field13;
            public T14 Field14;
            public T15 Field15;
        }
    }

    [Serializable]
    public struct Record<T0,T1,T2,T3,T4,T5,T6,T7,T8,T9,T10,T11,T12,T13,T14,T15,T16> : IRecord
    {
        public RecordHeader header;
        public RecordData[] recordData;
        private static Type[] _fieldTypes = new []{typeof(T0),typeof(T1),typeof(T2),typeof(T3),typeof(T4),typeof(T5),typeof(T6),typeof(T7),typeof(T8),typeof(T9),typeof(T10),typeof(T11),typeof(T12),typeof(T13),typeof(T14),typeof(T15),typeof(T16)};
        public RecordHeader Header { set => header = value; get => header; }
        public Type[] GetFieldTypes() => _fieldTypes;
        public IRecordData GetRecord(int rowIndex) => recordData[rowIndex];

        [Serializable]
        public struct RecordData : IRecordData
        {
            public RecordDataHeader header;
            public RecordDataHeader Header {set => header = value; get => header;}
            public T0 Field0;
            public T1 Field1;
            public T2 Field2;
            public T3 Field3;
            public T4 Field4;
            public T5 Field5;
            public T6 Field6;
            public T7 Field7;
            public T8 Field8;
            public T9 Field9;
            public T10 Field10;
            public T11 Field11;
            public T12 Field12;
            public T13 Field13;
            public T14 Field14;
            public T15 Field15;
            public T16 Field16;
        }
    }

    [Serializable]
    public struct Record<T0,T1,T2,T3,T4,T5,T6,T7,T8,T9,T10,T11,T12,T13,T14,T15,T16,T17> : IRecord
    {
        public RecordHeader header;
        public RecordData[] recordData;
        private static Type[] _fieldTypes = new []{typeof(T0),typeof(T1),typeof(T2),typeof(T3),typeof(T4),typeof(T5),typeof(T6),typeof(T7),typeof(T8),typeof(T9),typeof(T10),typeof(T11),typeof(T12),typeof(T13),typeof(T14),typeof(T15),typeof(T16),typeof(T17)};
        public RecordHeader Header { set => header = value; get => header; }
        public Type[] GetFieldTypes() => _fieldTypes;
        public IRecordData GetRecord(int rowIndex) => recordData[rowIndex];

        [Serializable]
        public struct RecordData : IRecordData
        {
            public RecordDataHeader header;
            public RecordDataHeader Header {set => header = value; get => header;}
            public T0 Field0;
            public T1 Field1;
            public T2 Field2;
            public T3 Field3;
            public T4 Field4;
            public T5 Field5;
            public T6 Field6;
            public T7 Field7;
            public T8 Field8;
            public T9 Field9;
            public T10 Field10;
            public T11 Field11;
            public T12 Field12;
            public T13 Field13;
            public T14 Field14;
            public T15 Field15;
            public T16 Field16;
            public T17 Field17;
        }
    }

    [Serializable]
    public struct Record<T0,T1,T2,T3,T4,T5,T6,T7,T8,T9,T10,T11,T12,T13,T14,T15,T16,T17,T18> : IRecord
    {
        public RecordHeader header;
        public RecordData[] recordData;
        private static Type[] _fieldTypes = new []{typeof(T0),typeof(T1),typeof(T2),typeof(T3),typeof(T4),typeof(T5),typeof(T6),typeof(T7),typeof(T8),typeof(T9),typeof(T10),typeof(T11),typeof(T12),typeof(T13),typeof(T14),typeof(T15),typeof(T16),typeof(T17),typeof(T18)};
        public RecordHeader Header { set => header = value; get => header; }
        public Type[] GetFieldTypes() => _fieldTypes;
        public IRecordData GetRecord(int rowIndex) => recordData[rowIndex];

        [Serializable]
        public struct RecordData : IRecordData
        {
            public RecordDataHeader header;
            public RecordDataHeader Header {set => header = value; get => header;}
            public T0 Field0;
            public T1 Field1;
            public T2 Field2;
            public T3 Field3;
            public T4 Field4;
            public T5 Field5;
            public T6 Field6;
            public T7 Field7;
            public T8 Field8;
            public T9 Field9;
            public T10 Field10;
            public T11 Field11;
            public T12 Field12;
            public T13 Field13;
            public T14 Field14;
            public T15 Field15;
            public T16 Field16;
            public T17 Field17;
            public T18 Field18;
        }
    }

    [Serializable]
    public struct Record<T0,T1,T2,T3,T4,T5,T6,T7,T8,T9,T10,T11,T12,T13,T14,T15,T16,T17,T18,T19> : IRecord
    {
        public RecordHeader header;
        public RecordData[] recordData;
        private static Type[] _fieldTypes = new []{typeof(T0),typeof(T1),typeof(T2),typeof(T3),typeof(T4),typeof(T5),typeof(T6),typeof(T7),typeof(T8),typeof(T9),typeof(T10),typeof(T11),typeof(T12),typeof(T13),typeof(T14),typeof(T15),typeof(T16),typeof(T17),typeof(T18),typeof(T19)};
        public RecordHeader Header { set => header = value; get => header; }
        public Type[] GetFieldTypes() => _fieldTypes;
        public IRecordData GetRecord(int rowIndex) => recordData[rowIndex];

        [Serializable]
        public struct RecordData : IRecordData
        {
            public RecordDataHeader header;
            public RecordDataHeader Header {set => header = value; get => header;}
            
            public T0 Field0;
            public T1 Field1;
            public T2 Field2;
            public T3 Field3;
            public T4 Field4;
            public T5 Field5;
            public T6 Field6;
            public T7 Field7;
            public T8 Field8;
            public T9 Field9;
            public T10 Field10;
            public T11 Field11;
            public T12 Field12;
            public T13 Field13;
            public T14 Field14;
            public T15 Field15;
            public T16 Field16;
            public T17 Field17;
            public T18 Field18;
            public T19 Field19;
        }
    }
}
