using System;
using System.Collections.Generic;
using System.Linq;
using ID;
using TinyDataTable;
using UnityEngine;

namespace TinyDataTable.Editor
{
    public static class ExportDataTableToCSharp
    {
        public static string Export( DataTable data , DataTableSettings settings , string assetPath )
        {
            string className = settings.className;
            CSharpCodeBuilder cb = new CSharpCodeBuilder();

            cb.AddComment("[WARNING]");
            cb.AddComment("This code is generated by TinyDataTable.");
            cb.AddComment("Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.");
            
            cb.AppendLine("#pragma warning disable CS0612");
            cb.AddUsing("System");
            cb.AddUsing("System.Linq");
            cb.AddUsing("UnityEngine");
            cb.AddUsing("System.Collections.Generic");
            cb.AddUsing("TinyDataTable");
            cb.AppendLine();
            
            using (cb.BeginNamespace(settings.namespaceName))
            {
                using (cb.AddAttribute("Serializable").BeginStruct(settings.className , inherit:$"IEquatable<{className}>, IEquatable<{className}.Enum>"))
                {
                    //Enum
                    using (cb.AddAttribute("Serializable").BeginEnum("Enum"))
                    {
                        var enums = data.Header.RowData
                            .Select(row => (row.Name, row.ID, row.Description))
                            .ToArray();
                        cb.AddEnums(enums);
                    }
                    cb.AppendLine();
                    
                    //プライベートメンバー
                    cb.AddComment("Private member");
                    cb.AddField("DataTableAsset" , "_dataTable" , "private static");
                    var assetPathStr =
                        string.IsNullOrEmpty(assetPath) ? "string.Empty" : $"\"{assetPath}\"";
                    cb.AddField("string" , $"_assetPath = {assetPathStr}" , "private static");
                    cb.AppendLine();
                    
                    //メンバー
                    cb.AddComment("Member");
                    cb.AddAttribute("SerializeField");
                    cb.AddField("Enum" , "_value" , "private");
                    cb.AddAttribute("NonSerialized");
                    cb.AddField("int" , "_index" , "private");
                    cb.AppendLine();
                    
                    //コンストラクター
                    cb.AddComment("Constructor");
                    using (cb.BeginConstructor(className, "Enum value, int index","private"))
                    {
                        cb.AddCode("this._value = value");
                        cb.AddCode("this._index = index");                        
                    }
                    cb.AppendLine();                    
                    cb.AddComment("Constructor");
                    using (cb.BeginConstructor(className, "Enum value",
                               "public" , "this(value, EnumToIndex(value))"))
                    {
                    }
                    cb.AppendLine();                    
                    cb.AddComment("Constructor");
                    using (cb.BeginConstructor(className, $"{className} value",
                               "public" , "this(value._value, value._index)"))
                    {
                    }                    
                    cb.AppendLine();
                    
                    cb.AddComment("Prepare");                    
                    using ( cb.BeginMethod("void", "Prepare" , "" , "private static") )
                    {
                        if (string.IsNullOrEmpty(assetPath) is false)
                        {
                            using (cb.BeginIf("_dataTable is null"))
                            {
                                cb.AddCode("var op = UnityEngine.AddressableAssets.Addressables.LoadAssetAsync<DataTableAsset>(_assetPath)");
                                cb.AddCode("DataTableAsset prefab = op.WaitForCompletion()");
                                cb.AddCode("_dataTable = prefab");
                            }
                        }
                    }
                    cb.AddComment("Index of this ID");                    
                    using (cb.BeginBlock("public int Index"))
                    {
                        using (cb.BeginBlock("get"))
                        {
                            using (cb.BeginIf("_index == 0"))
                            {
                                using (cb.BeginIf("_value == Enum.Invalid"))
                                {
                                    cb.AddCode("return 0");
                                }
                                cb.AddCode("_index = EnumToIndex(_value)");
                            }
                            cb.AddCode("return _index");                        
                        }
                    }
                    
                    //ValidIDList.Lengthで代用できるのでとりあえずオミット
//                    cb.AddComment("Size of record");
//                    cb.AddCode($"public static int Size => {data.Header.RowData.Length}");
                    cb.AddComment("Valid records");
                    cb.AddCode($"public static IReadOnlyList<{className}> ValidIDList => _validIDs");
                    cb.AddComment("Valid Enums");
                    cb.AddCode($"IReadOnlyList<{className}.Enum> ValidEnumList => _validEnums");
                    cb.AddComment("Is this record is valid");
                    cb.AddCode($"public bool IsValid => _index > 0 || _validEnums.Contains( _value )");
                    cb.AppendLine();
                    
                    cb.AddComment("record propieries");
                    foreach (var val in data.Header.RowData.Select( (header,idx) => (header,idx) ))
                    {
                        var name = val.header.Name;
                        var index = val.idx;
                        cb.AddCode($"public static {className} {name} {{ private set; get; }} = new {className}(Enum.{name}, {index})");
                    }
                    cb.AppendLine();
                    
                    //フィールドプロパティ
                    cb.AddComment("filed propieries");
                    foreach (var val in data.Columns.Select( (col,idx) => (col,idx) ))
                    {
                        var typename = val.col.Type.FullName;
                        var left = $"public {typename} {val.col.Name}";
                        var right = $"_dataTable.Data.GetCell<{typename}>({val.idx},_index == 0 ? Index : _index)";
                        cb.AddCode($"{left} => {right}");
                    }
                    cb.AppendLine();

                    //operators
                    cb.AddComment("operators");
                    cb.AddCode($"public bool Equals({className} other) => _value == other._value");
                    cb.AddCode($"public bool Equals({className}.Enum other) => _value == other");
                    cb.AddCode($"public override bool Equals(object obj) => obj is {className} other && Equals(other)");
                    cb.AddCode($"public override int GetHashCode() => (int)_value");
                    cb.AddCode($"public override string ToString() => _value.ToString()");
                    cb.AddCode($"public static bool operator ==({className} left, {className} right) => left.Equals(right)");
                    cb.AddCode($"public static bool operator !=({className} left, {className} right) => !left.Equals(right)");
                    cb.AddCode($"public static bool operator ==({className} left, {className}.Enum right) => left.Equals(right)");
                    cb.AddCode($"public static bool operator !=({className} left, {className}.Enum right) => !left.Equals(right)");
                    
  //                  cb.AddCode($"public static bool operator ==({className} left, {className} right) => left._value == right._value");
  //                  cb.AddCode($"public static bool operator !=({className} left, {className} right) => left._value != right._value");
  //                  cb.AddCode($"public static bool operator ==({className} left, {className}.Enum right) => left._value == right");
  //                  cb.AddCode($"public static bool operator !=({className} left, {className}.Enum right) => left._value != right");
  //                  cb.AddCode($"public static bool operator ==({className}.Enum left, {className} right) => left == right._value");
  //                  cb.AddCode($"public static bool operator !=({className}.Enum left, {className} right) => left != right._value");
                    cb.AddCode($"public static implicit operator {className}({className}.Enum value) => new {className}(value)");
                    cb.AddCode($"public static implicit operator {className}.Enum({className} value) => value._value");
                    cb.AppendLine();
                    
                    //静的テーブル
                    cb.AddComment("static id table");
                    using (cb.BeginBlock($"private static {className}[] _validIDs = new[]").Footer(";"))
                    {
                        foreach (var val in data.Header.RowData.Select((row,idx)=>(row,idx)))
                        {
                            if (val.row.ID > 0)
                            {
                                cb.AppendLine($"new {className}(Enum.{val.row.Name}, {val.idx}),");
                            }
                        }
                    }
                    cb.AppendLine();                    
                    cb.AddComment("static enum table");
                    using (cb.BeginBlock($"private static {className}.Enum[] _validEnums = new[]").Footer(";"))
                    {
                        foreach (var row in data.Header.RowData)
                        {
                            if (row.ID > 0)
                            {
                                cb.AppendLine($"Enum.{row.Name},");
                            }
                        }
                    }
                    //EnumをIndexに変換するメソッド（静的にテーブル展開されるので高速）
                    cb.AppendLine();                    
                    cb.AddComment("Enum to index");
                    using (cb.BeginBlock("private static int EnumToIndex(Enum value) => value switch").Footer(";"))
                    {
                        foreach (var val in data.Header.RowData.Select((row,idx)=>(row,idx)))
                        {
                             cb.AppendLine($"Enum.{val.row.Name} => {val.idx},");
                        }
                        cb.AppendLine($"_ => 0");
                    }                    
                }
            }

            return cb.ToString();
        }
    }
}


namespace ID
{
    [Serializable]
    public struct Hoge : IEquatable<Hoge> , IEquatable<Hoge.Enum>
    {
        [Serializable]
        public enum Enum
        {
            Invalid   = -1,
            data_0001 = 229732201,
            data_0002 = 46755367,
            data_0003 = 215973663,
            data_0004 = 712525871,
            data_0005 = 1161599732,
            data_0006 = 69262832,
            data_0007 = 1997597820,
            data_0008 = 1834241226,
            data_0009 = 976133618,
            data_0010 = 259131550,
        }

        // Private member
        private static DataTableAsset _dataTable;
        private static string _assetPath = "TinyDataTable/DataTableAsset.asset";

        // Member
        [SerializeField]
        private Enum _value;
        [NonSerialized]
        private int _index;

        // Constructor
        private Hoge(Enum value, int index)
        {
            this._value = value;
            this._index = index;
        }

        public Hoge(Enum value) : this(value, EnumToIndex(value))
        {
        }

        public Hoge(Hoge value) : this(value._value, value._index)
        {
        }

        // Prepare
        private static void Prepare()
        {
            if (_dataTable is null)
            {
                var op = UnityEngine.AddressableAssets.Addressables.LoadAssetAsync<DataTableAsset>(_assetPath);
                DataTableAsset prefab = op.WaitForCompletion();
                _dataTable = prefab;
            }
        }
        // Index of this ID
        public int Index
        {
            get
            {
                if (_index == 0)
                {
                    if (_value == Enum.Invalid)
                    {
                        return 0;
                    }
                    _index = EnumToIndex(_value);
                }
                return _index;
            }
        }
        // Size of record
        public static int Size => 11;
        // Valid records
        public static IReadOnlyList<Hoge> ValidIDList => _validIDs;
        // Valid Enums
        IReadOnlyList<Hoge.Enum> ValidEnumList => _validEnums;

        // record propieries
        public static Hoge Invalid { private set; get; } = new Hoge(Enum.Invalid, 0);
        public static Hoge data_0001 { private set; get; } = new Hoge(Enum.data_0001, 1);
        public static Hoge data_0002 { private set; get; } = new Hoge(Enum.data_0002, 2);
        public static Hoge data_0003 { private set; get; } = new Hoge(Enum.data_0003, 3);
        public static Hoge data_0004 { private set; get; } = new Hoge(Enum.data_0004, 4);
        public static Hoge data_0005 { private set; get; } = new Hoge(Enum.data_0005, 5);
        public static Hoge data_0006 { private set; get; } = new Hoge(Enum.data_0006, 6);
        public static Hoge data_0007 { private set; get; } = new Hoge(Enum.data_0007, 7);
        public static Hoge data_0008 { private set; get; } = new Hoge(Enum.data_0008, 8);
        public static Hoge data_0009 { private set; get; } = new Hoge(Enum.data_0009, 9);
        public static Hoge data_0010 { private set; get; } = new Hoge(Enum.data_0010, 10);

        // filed propieries
        public System.String STr => _dataTable.Data.GetCell<System.String>(0,_index == 0 ? Index : _index);
        public System.Int32 INT => _dataTable.Data.GetCell<System.Int32>(1,_index == 0 ? Index : _index);

        // filed propieries
        public bool Equals(Hoge other) => _value == other._value;
        public bool Equals(Hoge.Enum other) => _value == other;
        public override bool Equals(object obj) => obj is Hoge other && Equals(other);
        public override int GetHashCode() => (int)_value;
        public override string ToString() => _value.ToString();
        public static bool operator ==(Hoge left, Hoge right) => left.Equals(right);
        public static bool operator !=(Hoge left, Hoge right) => !left.Equals(right);
        public static bool operator ==(Hoge left, Hoge.Enum right) => left.Equals(right);
        public static bool operator !=(Hoge left, Hoge.Enum right) => !left.Equals(right);
        public static implicit operator Hoge(Hoge.Enum value) => new Hoge(value);
        public static implicit operator Hoge.Enum(Hoge value) => value._value;

        // static id table
        private static Hoge[] _validIDs = new[]
        {
            new Hoge(Enum.data_0001, 1),
            new Hoge(Enum.data_0002, 2),
            new Hoge(Enum.data_0003, 3),
            new Hoge(Enum.data_0004, 4),
            new Hoge(Enum.data_0005, 5),
            new Hoge(Enum.data_0006, 6),
            new Hoge(Enum.data_0007, 7),
            new Hoge(Enum.data_0008, 8),
            new Hoge(Enum.data_0009, 9),
            new Hoge(Enum.data_0010, 10),
        };

        // static enum table
        private static Hoge.Enum[] _validEnums = new[]
        {
            Enum.data_0001,
            Enum.data_0002,
            Enum.data_0003,
            Enum.data_0004,
            Enum.data_0005,
            Enum.data_0006,
            Enum.data_0007,
            Enum.data_0008,
            Enum.data_0009,
            Enum.data_0010,
        };

        // Enum to index
        private static int EnumToIndex(Enum value) => value switch
        {
            Enum.Invalid => 0,
            Enum.data_0001 => 1,
            Enum.data_0002 => 2,
            Enum.data_0003 => 3,
            Enum.data_0004 => 4,
            Enum.data_0005 => 5,
            Enum.data_0006 => 6,
            Enum.data_0007 => 7,
            Enum.data_0008 => 8,
            Enum.data_0009 => 9,
            Enum.data_0010 => 10,
            _ => 0
        };
    }
}
