using System;
using System.Collections.Generic;
using System.Linq;
using TinyDataTable;
using UnityEngine;

namespace TinyDataTable.Editor
{
    public static partial class ExportDataTableToCSharp
    {
        public static string Export( DataTableAsset asset ,string className,string namespaceName , string resourcePath , string addressName )
        {
            var data = asset.Data;
            CSharpCodeBuilder cb = new CSharpCodeBuilder();

            cb.AddComment("[TYNY_DATA_TABLE][1.0.0]");
            cb.AddComment("This code is generated by TinyDataTable.");
            cb.AddComment("Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.");
            
            cb.AppendLine("#pragma warning disable CS0612");
            cb.AddUsing("System");
            cb.AddUsing("System.Linq");
            cb.AddUsing("UnityEngine");
            cb.AddUsing("System.Collections.Generic");
            cb.AddUsing("TinyDataTable");
            cb.AppendLine();
            
            using (cb.BeginNamespace(namespaceName))
            {
                cb.AddAttribute("Serializable");
                using (cb.BeginStruct(className , inherit:$"IIdentifier, IEquatable<{className}>, IEquatable<{className}.Enum>", isPartial:true))
                {
                    //Enum
                    using (cb.AddAttribute("Serializable").BeginEnum("Enum"))
                    {
                        var enums = data.Header.RowData
                            .Select((row,i) => ($"[EnumOrder({i})] {row.Name}", $"0x{row.ID:X8}", row.Description,row.Obsolete?"Obsolete":""))
                            .ToArray();
                        cb.AddEnums(enums);
                    }
                    cb.AppendLine();
                    
                    //プライベートメンバー
                    cb.AddComment("Private member");
                    cb.AddField("DataTableAsset" , "_dataTable" , "private static");
                    var assetPathStr = "null";
                    if(string.IsNullOrEmpty(addressName) is false) assetPathStr = $"\"{addressName}\"";
                    if(string.IsNullOrEmpty(resourcePath) is false) assetPathStr = $"\"{resourcePath}\"";
                    cb.AddField("string" , $"_assetPath = {assetPathStr}" , "private const");
                    cb.AppendLine();
                    
                    //メンバー
                    cb.AddComment("Member");
                    cb.AddAttribute("SerializeField");
                    cb.AddField("Enum" , "_value" , "private");
                    cb.AddAttribute("NonSerialized");
                    cb.AddField("int" , "_index" , "private");
                    cb.AppendLine();
                    
                    //コンストラクター
                    cb.AddComment("Constructor");
                    using (cb.BeginConstructor(className, "Enum value, int index","private"))
                    {
                        cb.AddCode("this._value = value");
                        cb.AddCode("this._index = index");                        
                    }
                    cb.AppendLine();
                    cb.AddComment("Constructor");
                    using (cb.BeginConstructor(className, "Enum value",
                               "public" , "this(value, EnumToIndex(value))"))
                    {
                    }
                    cb.AppendLine();
                    cb.AddComment("Constructor");
                    using (cb.BeginConstructor(className, $"{className} value",
                               "public" , "this(value._value, value._index)"))
                    {
                    }                    
                    cb.AppendLine();

                    if (string.IsNullOrEmpty(addressName) is false)
                    {
                        cb.AddComment("Prepare(Addressables)");
                        using (cb.BeginMethod("void", "Prepare", "", "public static"))
                        {
                            if (string.IsNullOrEmpty(addressName) is false)
                            {
                                using (cb.BeginIf("_dataTable is null"))
                                {
                                    cb.AddCode(
                                        "var op = UnityEngine.AddressableAssets.Addressables.LoadAssetAsync<DataTableAsset>(_assetPath)");
                                    cb.AddCode("DataTableAsset prefab = op.WaitForCompletion()");
                                    cb.AddCode("_dataTable = prefab");
                                }
                            }
                        }
                    }
                    else if (string.IsNullOrEmpty(resourcePath) is false)
                    {
                        cb.AddComment("Prepare(Resources)");
                        using (cb.BeginMethod("void", "Prepare", "", "public static"))
                        {
                            using (cb.BeginIf("_dataTable is null"))
                            {
                                cb.AddCode($"var prefab = UnityEngine.Resources.Load<DataTableAsset>(_assetPath)");
                                cb.AddCode("_dataTable = prefab");
                            }
                        }                        
                    }
                    else
                    {
                        cb.AddComment("Prepare");
                        using (cb.BeginMethod("void", "Prepare", "", "public static"))
                        {
                        }
                    }

                    cb.AddComment("Terminate");
                    using (cb.BeginMethod("void", "Terminate", "", "public static"))
                    {
                        using (cb.BeginIf("_dataTable != null"))
                        {
                            cb.AddCode("_dataTable = null");
                        }
                    }

                    cb.AddComment("Index of this ID");                    
                    using (cb.BeginBlock("public int Index"))
                    {
                        using (cb.BeginBlock("get"))
                        {
                            using (cb.BeginIf("_index == 0"))
                            {
                                using (cb.BeginIf("_value == Enum.Invalid"))
                                {
                                    cb.AddCode("return 0");
                                }
                                cb.AddCode("_index = EnumToIndex(_value)");
                            }
                            cb.AddCode("return _index");                        
                        }
                    }
                    
                    //ValidIDList.Lengthで代用できるのでとりあえずオミット
//                    cb.AddComment("Size of record");
//                    cb.AddCode($"public static int Size => {data.Header.RowData.Length}");
                    cb.AddComment("Valid records");
                    cb.AddCode($"public static IReadOnlyList<{className}> ValidIDList => _validIDs");
                    cb.AddComment("Valid Enums");
                    cb.AddCode($"IReadOnlyList<{className}.Enum> ValidEnumList => _validEnums");
                    cb.AddComment("Is this record is valid");
                    cb.AddCode($"public bool IsValid => _validEnums.Contains( _value )");
                    cb.AppendLine();

                    cb.AddComment("record propieries");
                    
                    foreach (var val in data.Header.RowData.Select( (header,idx) => (header,idx) ))
                    {
                        var name = val.header.Name;
                        var index = val.idx;
                        if (val.header.Obsolete)
                        {
                            cb.AppendLine("[Obsolete]");
                        }
                        cb.AddCode($"public static {className} {name} {{ private set; get; }} = new {className}(Enum.{name}, {index})");
                    }
                    cb.AppendLine();
                    
                    //フィールドプロパティ
                    //関数呼び出しを避けるためにインラインで３項演算子を使う
                    cb.AddComment("filed propieries");
                    foreach (var val in data.Columns.Select( (col,idx) => (col,idx) ))
                    {
                        if (val.col.Obsolete)
                        {
                            cb.AppendLine("[Obsolete]");
                        }
                        var typename = val.col.Type.FullName;
                        var left = $"public {typename} {val.col.Name}";
                        var right = $"_dataTable.Data.GetCell<{typename}>({val.idx},_index == 0 ? Index : _index)";
                        cb.AddCode($"{left} => {right}");
                    }
                    cb.AppendLine();

                    //operators
                    cb.AddComment("operators");
                    cb.AddCode($"public bool Equals({className} other) => _value == other._value");
                    cb.AddCode($"public bool Equals({className}.Enum other) => _value == other");
                    cb.AddCode($"public override bool Equals(object obj) => obj is {className} other && Equals(other)");
                    cb.AddCode($"public override int GetHashCode() => (int)_value");
                    cb.AddCode($"public override string ToString() => _value.ToString()");
                    cb.AddCode($"public static bool operator ==({className} left, {className} right) => left.Equals(right)");
                    cb.AddCode($"public static bool operator !=({className} left, {className} right) => !left.Equals(right)");
                    cb.AddCode($"public static bool operator ==({className} left, {className}.Enum right) => left.Equals(right)");
                    cb.AddCode($"public static bool operator !=({className} left, {className}.Enum right) => !left.Equals(right)");
                    
  //                  cb.AddCode($"public static bool operator ==({className} left, {className} right) => left._value == right._value");
  //                  cb.AddCode($"public static bool operator !=({className} left, {className} right) => left._value != right._value");
  //                  cb.AddCode($"public static bool operator ==({className} left, {className}.Enum right) => left._value == right");
  //                  cb.AddCode($"public static bool operator !=({className} left, {className}.Enum right) => left._value != right");
  //                  cb.AddCode($"public static bool operator ==({className}.Enum left, {className} right) => left == right._value");
  //                  cb.AddCode($"public static bool operator !=({className}.Enum left, {className} right) => left != right._value");
                    cb.AddCode($"public static implicit operator {className}({className}.Enum value) => new {className}(value)");
                    cb.AddCode($"public static implicit operator {className}.Enum({className} value) => value._value");
                    cb.AppendLine();
                    
                    //静的テーブル
                    cb.AddComment("static id table");
                    var validIDs = data.Header.RowData
                        .Select((row, idx) => (row, idx))
                        .Where( t => t.idx > 0);
                    if (validIDs.Any())
                    {
                        using (cb.BeginBlock($"private static {className}[] _validIDs = new[]").Footer(";"))
                        {

                            foreach (var val in validIDs)
                            {
                                cb.AppendLine($"{className}.{val.row.Name},");
                            }
                        }
                    }
                    else
                    {
                        cb.AddCode(($"private static {className}[] _validIDs = Array.Empty<{className}>()"));
                    }

                    cb.AppendLine();                    
                    cb.AddComment("static enum table");
                    var validEnums = data.Header.RowData
                        .Where(t => t.ID > 0 );
                    if (validEnums.Any())
                    {
                        using (cb.BeginBlock($"private static {className}.Enum[] _validEnums = new[]").Footer(";"))
                        {
                            foreach (var row in validEnums)
                            {
                                cb.AppendLine($"Enum.{row.Name},");
                            }
                        }
                    }
                    else
                    {
                        cb.AddCode(($"private static {className}.Enum[] _validEnums = Array.Empty<{className}.Enum>()"));
                    }

                    cb.AppendLine();
                    //EnumをIndexに変換するメソッド（静的にテーブル展開されるので高速）
                    cb.AddComment("Enum to index");
                    
                    using (cb.BeginBlock("private static int EnumToIndex(Enum value) => value switch").Footer(";"))
                    {
                        foreach (var val in data.Header.RowData.Select((row,idx)=>(row,idx)))
                        {
                             cb.AppendLine($"Enum.{val.row.Name} => {val.idx},");
                        }
                        cb.AppendLine($"_ => 0");
                    }
                    cb.AppendLine();

                    cb.AddComment("AssetTags");
                    using (cb.BeginBlock("private static string[] _assetTags = new string[]").Footer(";"))
                    {
                        var tags = String.Join(",", asset.Tags.Select(t=>$"\"{t}\"") );
                        cb.AppendLine(tags);                        
                    }
                    cb.AddCode("public static bool HasTag(string tag) => _assetTags.Contains(tag)");
                    cb.AppendLine();
                    
                    //プロパティドロワー（仮）
                    using (cb.BeginIfdef("UNITY_EDITOR"))
                    {
                        cb.AppendLine($"[UnityEditor.CustomPropertyDrawer(typeof({className}))]");
                        using (cb.BeginClass($"{className}PropertyDrawer" , "private" ,$"TinyDataTable.Editor.IDPropertyDrawerBase<{className}.Enum>" ))
                        {
                        }
                    }
                }
            }
            return cb.ToString();
        }
    }
}
